// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaq8Qa--BSEcCgxH7Ieltsp1xybpMsyq0',
    appId: '1:864960603826:android:2a7e81c94a443ab92d4bab',
    messagingSenderId: '864960603826',
    projectId: 'gamma-86108',
    storageBucket: 'gamma-86108.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkyX6CCLegvEnxBePaJEHXhg-bPM8zWPw',
    appId: '1:864960603826:ios:5af599581d168ee02d4bab',
    messagingSenderId: '864960603826',
    projectId: 'gamma-86108',
    storageBucket: 'gamma-86108.firebasestorage.app',
    iosBundleId: 'com.ava.hospital.avaApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOPRUzrKtJokhzX48mJBJ-w7qLpvxglE',
    appId: '1:864960603826:web:77d5821ca66bdf3e2d4bab',
    messagingSenderId: '864960603826',
    projectId: 'gamma-86108',
    authDomain: 'gamma-86108.firebaseapp.com',
    storageBucket: 'gamma-86108.firebasestorage.app',
    measurementId: 'G-J0FBDT56G5',
  );
}
